title: "Мой сайт"
description: "Описание сайта"
baseurl: "/docs"  # если сайт находится в подпапке

# Отключите стандартную тему
theme: null

# Настройки Markdown (используйте либо kramdown, либо CommonMark)
markdown: CommonMark
commonmark:
  extensions:
    - table
    - strikethrough
    - mermaid

# Явно укажите использовать ваш шаблон
defaults:
  - scope:
      path: ""  # для всех файлов
    values:
      layout: default

exclude:
  - README.md